name: Deploy Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Sesuaikan dengan server (log kamu tadi pakai 8.3)
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      # Action ini otomatis menangani ssh-agent dan SSH_AUTH_SOCK
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts (host key)
        run: |
          mkdir -p ~/.ssh
          # Scan berdasarkan hostname dan IP sekaligus
          ssh-keyscan -H ruangai-staging.appdata.id >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Install Deployer
        run: |
          curl -LO https://deployer.org/releases/v7.5.12/deployer.phar
          chmod +x deployer.phar

      - name: Deploy Production
        run: php deployer.phar deploy production -vvv --no-interaction